### PR TITLE
Disable warning about incomplete limits header

### PR DESCRIPTION
**Pull request by matthijskooijman**
This is essentially a copy of
https://github.com/maniacbug/StandardCplusplus/commit/2f07cf6735fc325906e6f626a904d7c988fbc1e2

This also adds a note to the README, which seems like a better place for
this.

### CODE REVIEW

**Comment by HendryKaak** [comment]
Is it possible for you to merge this PR? @mike-matera 
This warning is quite annoying during development, since it shows up multiple times in the compiler output :")

**Comment by mike-matera** [comment]
Hello! Thank you so much for the PR. I am not going to merge it because the problem is with upstream (uClibC++) and that the warning are important and should be heeded. I'm sorry for the annoyance but it's better to be annoyed than to release buggy software.

**Comment by neu-rah** [comment]
another solution would be to complete the limits header

**Comment by matthijskooijman** [comment]
I just noticed that there is again some development (and even a new release 0.2.5 last week, the first since 2012 AFAICS). So that might make a fix upstream perhaps feasible, if anyone has some time for that.

Alternatively, a workaround could be to check for a macro, e.g. `NO_WARNING_LIMITS_INCOMPLETE` and if it is defined, skip the warning. This workaround would best be placed upstream, but maybe adding it here would be easier.

**Pull request closed without merging**
